# Create environment:
# $ conda env create --force
name: project_nlp
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python = 3.5
  - ipython > 5.0
  - jupyter
  - numpy
  - nltk
  - textblob
  - spacy
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - tensorflow
  - setuptools
  - plotly
  - gensim
  - pip
  - rise
  - pip:
      - ftfy 
      - nbbrowserpdf
      - ipython-sql
      - tabulate
      - pytagcloud
      - pygame
      - simplejson
      #- wordcloud # => https://github.com/amueller/word_cloud
    
# Start environment:
# $ source activate project_nlp